# root.hcl — inherited by every stack via find_in_parent_folders("root.hcl")
#
# Responsibilities:
#   1. Configure the GCS remote state backend
#   2. Auto-generate provider.tf for every stack
#   3. Pass shared inputs down to all stacks

locals {
  tenant = "swpt"

  # region.hcl lives at regions/<region>/region.hcl — always in the parent chain
  region_cfg   = read_terragrunt_config(find_in_parent_folders("region.hcl"))
  region_name  = local.region_cfg.locals.region
  region_short = local.region_cfg.locals.region_short

  # env.hcl lives at regions/<region>/<env>/env.hcl — always in the parent chain
  env_cfg    = read_terragrunt_config(find_in_parent_folders("env.hcl"))
  env_name   = local.env_cfg.locals.env
  project_id = local.env_cfg.locals.project_id
}

remote_state {
  backend = "gcs"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
  config = {
    bucket   = "${local.tenant}-${local.region_short}-infra-${local.env_name}-tf"
    prefix   = path_relative_to_include()
    project  = local.project_id
    location = local.region_name
  }
}

generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
# Generated by root.hcl — provides project/region to all stacks.
# Provider VERSION requirements live in each module's versions.tf.
provider "google" {
  project = "${local.project_id}"
  region  = "${local.region_name}"
}
EOF
}

inputs = merge(
  local.region_cfg.locals,
  local.env_cfg.locals,
  { tenant = local.tenant },
)
